resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:berinle/concourse-spring-boot-gradle.git
      branch: master

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/ci/tasks/package.yml
