---
resources:
  - name: source-code
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}
  - name: deploy-web-app
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: package
    plan:
    - get: source-code
      trigger: true
    - task: package
      privileged: true
      file: source-code/ci/tasks/package.yml
#    - put: deploy-web-app
#      params:
#        manifest: source-code/manifest.yml
